<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOwkvvm6\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOwkvvm6/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOwkvvm6.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOwkvvm6\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerOwkvvm6\installerProdDebugProjectContainer(array(
    'container.build_hash' => 'Owkvvm6',
    'container.build_id' => 'e7fae6c2',
    'container.build_time' => 1516466663,
));
