<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9gc6ylg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9gc6ylg/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9gc6ylg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9gc6ylg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9gc6ylg\appProdProjectContainer(array(
    'container.build_hash' => '9gc6ylg',
    'container.build_id' => '7ad10410',
    'container.build_time' => 1516466482,
));
