<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\ActionHandler\CodeSnippet' shared autowired service.

return $this->services['Pimcore\Targeting\ActionHandler\CodeSnippet'] = new \Pimcore\Targeting\ActionHandler\CodeSnippet(new \Pimcore\Http\Response\CodeInjector(${($_ = isset($this->services['Pimcore\Http\ResponseHelper']) ? $this->services['Pimcore\Http\ResponseHelper'] : $this->services['Pimcore\Http\ResponseHelper'] = new \Pimcore\Http\ResponseHelper()) && false ?: '_'}));
