<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Manager' shared autowired service.

return $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Manager'] = new \Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Manager(new \Pimcore\DependencyInjection\CollectionServiceLocator(array('Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\DataObjects' => function () {
    return ${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\DataObjects']) ? $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\DataObjects'] : $this->load(__DIR__.'/getDataObjectsService.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\PimcoreUsers' => function () {
    return ${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers']) ? $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers'] : $this->load(__DIR__.'/getPimcoreUsersService.php')) && false ?: '_'};
}, 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\SentMail' => function () {
    return ${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail']) ? $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail'] : $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail'] = new \Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail()) && false ?: '_'};
})));
