<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.c44ncgs' shared service.

return $this->services['service_locator.c44ncgs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('pimcoreUsers' => function () {
    $f = function (\Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers']) ? $this->services['Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers'] : $this->load(__DIR__.'/getPimcoreUsersService.php')) && false ?: '_'});
}));
