<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Install\Command\InstallCommand' shared autowired service.

return $this->services['Pimcore\Install\Command\InstallCommand'] = new \Pimcore\Install\Command\InstallCommand(${($_ = isset($this->services['Pimcore\Install\Installer']) ? $this->services['Pimcore\Install\Installer'] : $this->load(__DIR__.'/getInstallerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Install\Profile\ProfileLocator']) ? $this->services['Pimcore\Install\Profile\ProfileLocator'] : $this->load(__DIR__.'/getProfileLocatorService.php')) && false ?: '_'});
