<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Install\Installer' shared autowired service.

return $this->services['Pimcore\Install\Installer'] = new \Pimcore\Install\Installer(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load(__DIR__.'/getLoggerService.php')) && false ?: '_'}, ${($_ = isset($this->services['Pimcore\Install\Profile\ProfileLocator']) ? $this->services['Pimcore\Install\Profile\ProfileLocator'] : $this->load(__DIR__.'/getProfileLocatorService.php')) && false ?: '_'});
