<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Install\Controller\InstallController' shared autowired service.

$this->services['Pimcore\Install\Controller\InstallController'] = $instance = new \Pimcore\Install\Controller\InstallController(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load(__DIR__.'/getLoggerService.php')) && false ?: '_'});

$instance->setContainer($this);

return $instance;
