<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Composer\PackageInfo' shared autowired service.

return $this->services['Pimcore\Composer\PackageInfo'] = new \Pimcore\Composer\PackageInfo();
