<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'uri_signer' shared service.

return $this->services['uri_signer'] = new \Symfony\Component\HttpKernel\UriSigner('installer-5a6371e6d17899.07252620');
