<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Tool\AssetsInstaller' shared autowired service.

return $this->services['Pimcore\Tool\AssetsInstaller'] = new \Pimcore\Tool\AssetsInstaller(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'}, ${($_ = isset($this->services['pimcore_admin.serializer']) ? $this->services['pimcore_admin.serializer'] : $this->load(__DIR__.'/getPimcoreAdmin_SerializerService.php')) && false ?: '_'});
