<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Model\Schedule\Manager\Procedural' shared autowired service.

return $this->services['Pimcore\Model\Schedule\Manager\Procedural'] = new \Pimcore\Model\Schedule\Manager\Procedural('maintenance.pid', ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
