<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.cb6lrrq' shared service.

return $this->services['service_locator.cb6lrrq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('siteConfigProvider' => function () {
    $f = function (\Pimcore\Analytics\Google\Config\SiteConfigProvider $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Analytics\Google\Config\SiteConfigProvider']) ? $this->services['Pimcore\Analytics\Google\Config\SiteConfigProvider'] : $this->load(__DIR__.'/getSiteConfigProviderService.php')) && false ?: '_'});
}));
