<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ibcgzo7' shared service.

return $this->services['service_locator.ibcgzo7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('assetsInstaller' => function () {
    $f = function (\Pimcore\Tool\AssetsInstaller $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Tool\AssetsInstaller']) ? $this->services['Pimcore\Tool\AssetsInstaller'] : $this->load(__DIR__.'/getAssetsInstallerService.php')) && false ?: '_'});
}));
